import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const SecretPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>This is a secret page</main>

      <footer className={styles.footer}>
        <div>this is a footer</div>
      </footer>
    </div>
  );
};

export default SecretPage;
